C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\dto\UserDTO.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\resources\ChallengeResourse.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\UserService.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\repositories\ContextRepository.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\resources\ContextResourse.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\exceptions\DataAlreadyExistsException.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\config\TestConfig.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\ContextService.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\exceptions\ObjectNotFoundException.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\SisalfaService.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\config\ProdConfig.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\resources\exceptions\ValidationError.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\dto\ChallengeNewDTO.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\mock\SisalfaMockService.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\resources\UserResourse.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\exceptions\DataNotFoundException.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\domain\Challenge.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\domain\Context.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\config\DevConfig.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\resources\exceptions\StandardError.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\dto\ContextDTO.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\repositories\ChallengeRepository.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\ChallengeService.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\EducAPIApplication.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\domain\User.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\dto\ContextNewDTO.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\resources\exceptions\ResourceExceptionHandler.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\repositories\UserRepository.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\dto\ChallengeDTO.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\DBService.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\resources\exceptions\FieldMessage.java
C:\Users\raimundo.marcos\Documents\EducAPI\src\main\java\br\ufpb\dcx\apps4society\educapi\services\exceptions\DataIntegrityException.java
